version: '3'

services:
  web:
    restart: always
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    image: app-rq
    volumes:
      - shared-data:/data
    ports:
      - 5000:5000
    networks:
      - my-network
    command: gunicorn -b :5000 test_server:app

  worker:
    image: app-rq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - shared-data:/data
    networks:
      - my-network
    depends_on:
      - redis
    command: rqworker --name worker --url redis://redis:6379/0

  redis:
    image: redis
    networks:
      - my-network

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - my-network
    environment:
      - POSTGRES_PASSWORD=lol
      - POSTGRES_DB=videos

volumes:
  shared-data:

networks:
  my-network:
    driver: bridge
