#!/usr/bin/env bash
#SBATCH -A SNIC2020-33-20 -p alvis
#SBATCH -n 1
#SBATCH --gpus-per-node=T4:1
#SBATCH -t 2-0 # 2 days

vid=$HOME/vids/025_FL_R.MOV
cp $HOME/motion-analysis $TMPDIR
cp $vid $TMPDIR

cd $TMPDIR

module load GCC/8.3.0 CUDA/10.1.243 OpenMPI/3.1.4 PyTorch/1.4.0-Python-3.7.4 SciPy-bundle/2019.10-Python-3.7.4

cd motion-analysis
./install.sh cluster

pythonpath="$(which python)"
export PYTHONPATH=$PYTHONPATH:$pythonpath/lib/python3.6/site-packages/
export PATH=$PATH:$pythonpath/bin
