#!/usr/bin/env bash
#SBATCH -A SNIC2020-33-20 -p alvis
#SBATCH -n 1
#SBATCH --gpus-per-node=T4:1
#SBATCH -t 2-0 # 2 days

vid="025_FL_R.MOV"

cp -r $HOME/motion-analysis $TMPDIR
cp -r $HOME/vid/$vid $TMPDIR

cd $TMPDIR
mkdir results

module load GCC/8.3.0 CUDA/10.1.243 OpenMPI/3.1.4 PyTorch/1.4.0-Python-3.7.4 SciPy-bundle/2019.10-Python-3.7.4

cd motion-analysis
./install.sh cluster

pythonpath="$(which python)"
export PYTHONPATH=$PYTHONPATH:$pythonpath/lib/python3.6/site-packages/
export PATH=$PATH:$pythonpath/bin

cd pose/analysis

./run-detection-cluster.sh

cd $TMPDIR
cp -r results $HOME/results

