#!/usr/bin/env bash
#SBATCH -A SNIC2020-33-20 -p alvis
#SBATCH -n 4
#SBATCH --gpus-per-node=T4:1
#SBATCH -t 0-5:00:0 # 5 h 

data_set="data_Octavio-Paz.npz"
archive="VA-classification"
data_set="data_"$2".npz"
classifier=$1
itr="_itr_"$3
train_idx="train-idx-val.npy"
test_idx="test-idx-val.npy"
train_idx="indices.npz"
test_idx=""

cp -r $HOME/motion-analysis $TMPDIR
cp -r $HOME/datasets $TMPDIR
cp $HOME/datasets/$train_idx $TMPDIR
cd $TMPDIR
mkdir results

module purge
module load GCC/8.3.0 CUDA/10.1.243 OpenMPI/3.1.4 cuDNN/7.6.4.38
#module load GCC/8.3.0 CUDA/10.1.243 OpenMPI/3.1.4 TensorFlow/2.1.0-Python-3.7.4 
module load SciPy-bundle/2019.10-Python-3.7.4 matplotlib/3.1.1-Python-3.7.4
#module load Keras/2.3.1-Python-3.7.4

virtualenv train-class
source train-class/bin/activate

pip install tensorflow==2.3.1
pip install keras==2.4
pip install -U --no-deps git+https://github.com/ck37/coral-ordinal/
#cd motion-analysis/tsc/dl-4-tsc
cd motion-analysis/classification/tsc

pip install -r utils/requirements-cluster.txt


python train-classifier.py $TMPDIR/results $TMPDIR/datasets/$data_set $classifier --itr $itr --gen_idx t

#python train-classifier.py $TMPDIR/results $TMPDIR/$data_set $classifier --train_idx $TMPDIR/$train_idx --test_idx $TMPDIR/$test_idx --itr $itr

cp -r $TMPDIR/results/. $HOME/training/
