version: '3'

services:
  web:
    build: ./app
    image: master-image
    ports:
      - 5000:5000
    command: gunicorn -b :5000 app:app

  worker:
    image: master-image
    depends_on:
      - redis
    command: rqworker --name worker --url redis://redis:6379/0

  redis:
    image: redis
